#!/bin/bash

wget https://datahub.io/machine-learning/iris/r/iris.csv

# wget -qO- \
#      "https://yihui.org/tinytex/install-unx.sh" | \
#      sh -s - --admin --no-path \
#    && mv ~/.TinyTeX /opt/TinyTeX \
#    && /opt/TinyTeX/bin/*/tlmgr path add \
#    && tlmgr install metafont mfware inconsolata tex ae parskip listings pgf preview grfext \
#    && tlmgr install standalone luatex85 pgfplots \
#    && tlmgr path add \
#    && chown -R root:staff /opt/TinyTeX \
#    && chmod -R g+w /opt/TinyTeX \
#    && chmod -R g+wx /opt/TinyTeX/bin

# sed -i 's/256MiB/2GiB/' /etc/ImageMagick-6/policy.xml

# exec "$@"
